### ISSUE TITLE
Form shortname field showing previous field value after unsuccessful form submision

### ISSUE THREAD

**Issue by MussabTanveer** [MussabTanveer/custom#1]
Form unsuccessful submission is not populating the shortname fied with correct value. The issue is in 3 add forms:
* [framework](https://github.com/MussabTanveer/custom/blob/d61caa785f3a90e2d746732dc68604932448f7b7/add_framework.php)
* [peo](https://github.com/MussabTanveer/custom/blob/d61caa785f3a90e2d746732dc68604932448f7b7/add_peo.php)
* [plo](https://github.com/MussabTanveer/custom/blob/d61caa785f3a90e2d746732dc68604932448f7b7/add_plo.php)

**Comment by syedkhizarulhaq-cis** [comment]
bug was due to the usage of variable $shortname in two different places in the same file :)
